package com.example.urbanmaintenancemanager.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors
val PrimaryLight = Color(0xFF00658E)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFC7E7FF)
val OnPrimaryContainerLight = Color(0xFF001E2E)
val SecondaryLight = Color(0xFF4F616E)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFD2E5F5)
val OnSecondaryContainerLight = Color(0xFF0B1E29)
val TertiaryLight = Color(0xFF62597C)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFE8DDFF)
val OnTertiaryContainerLight = Color(0xFF1E1635)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)
val BackgroundLight = Color(0xFFF6FAFE)
val OnBackgroundLight = Color(0xFF181C1F)
val SurfaceLight = Color(0xFFF6FAFE)
val OnSurfaceLight = Color(0xFF181C1F)
val SurfaceVariantLight = Color(0xFFDDE3EA)
val OnSurfaceVariantLight = Color(0xFF41484D)
val OutlineLight = Color(0xFF71787E)

// Dark Theme Colors
val PrimaryDark = Color(0xFF8DCDFF)
val OnPrimaryDark = Color(0xFF00344C)
val PrimaryContainerDark = Color(0xFF004C6C)
val OnPrimaryContainerDark = Color(0xFFC7E7FF)
val SecondaryDark = Color(0xFFB6C9D8)
val OnSecondaryDark = Color(0xFF21333E)
val SecondaryContainerDark = Color(0xFF374955)
val OnSecondaryContainerDark = Color(0xFFD2E5F5)
val TertiaryDark = Color(0xFFCCC1E9)
val OnTertiaryDark = Color(0xFF332B4B)
val TertiaryContainerDark = Color(0xFF4A4263)
val OnTertiaryContainerDark = Color(0xFFE8DDFF)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val BackgroundDark = Color(0xFF101417)
val OnBackgroundDark = Color(0xFFE0E3E7)
val SurfaceDark = Color(0xFF101417)
val OnSurfaceDark = Color(0xFFE0E3E7)
val SurfaceVariantDark = Color(0xFF41484D)
val OnSurfaceVariantDark = Color(0xFFC1C7CE)
val OutlineDark = Color(0xFF8B9298) 